### ISSUE TITLE
Run in browser

### ISSUE THREAD

**Issue by rabet** [aloysius-pgast/bittrex-signalr-client#12]
Hi, thanks for this nice lib. 
Please it is possible to somehow run (build for) it in broswser (not node)?

Thanks a lot!

**Comment by aloysius-pgast** [comment]
Hi. Glad you like it. 

Sorry but lib is not meant to run in browser and I don't plan to support it. 

That being said, it all depends on what you're trying to achieve from the browser. Maybe running an instance of https://github.com/aloysius-pgast/crypto-exchanges-gateway and subscribing to it from the browser might be a solution (gateway is meant to do most of the hard work of connecting to the exchanges, so that we can have simpler clients)
