### ISSUE TITLE
trades causing very high bandwidth

### ISSUE THREAD

**Issue by vaseo1** [aloysius-pgast/bittrex-signalr-client#15]
Great tool!
Only issue I'm experiencing is very high download bandwidth when subscribed to trades.

Subscribing to all available markets (trades only) gives about 1.5Mbit permanent download in average, this is definitely way more than the data I get in the form of the subscribed trades.
For example CryptoCompareAPI uses about 100Kbit for all markets trades for multiple exchanges, not just bittrex!

Maybe something to look into.
Haven't tried using the exchanges-gateway but I suspect the same result as it uses this client for bittrex if I understood it right.

Cheers!

**Comment by aloysius-pgast** [comment]
Hi. I suspect the difference with crypto compare is because Bittrex returns orderbooks and trades at the same time which make it more verbose. Even if there is no FILL, you’ll get data every time BID/ASK changes. Not sure much can be done for this unfortunately. I think there is a method to only retrieve summary data, I’ll check if it could be use to retrieve trades only.

**Comment by aloysius-pgast** [comment]
Hi. I confirm there is no way to subscribe only to trades using Bittrex api. Until they provide a way to do it, nothing can be done to reduce bandwidth.
