### ISSUE TITLE
Lack of documentation

### ISSUE THREAD

**Issue by artbred** [aloysius-pgast/bittrex-signalr-client#19]
Hello, i have a one question and it will be great if you answer it
In constructor i use resyncOrderBooksAutomatically, however i do not get how to catch those resyncs and store them in my variable?

**Comment by aloysius-pgast** [comment]
Hi
When order book is resynched, an `orderBook`event (containing full order book) will be emitted intead of an `orderBookUpdate`event which only contains a delta. Default behaviour for the library (since the beginning) is to resync automatically when a missing *Nounce* has been found. But when subscribing to many pairs (300 pairs for example), it's easy to miss *Nounces* and resynching every time would just increase the problem. That's why `resyncOrderBooksAutomatically`has been introduced recently to disable automatic resync.

**Comment by artbred** [comment]
Great i Got it. And resyncOrderBooksAutomatically works when there are some updates inside the order book or when? Also if im using client.resyncOrderBooks how do i catch updates, with orderBook event?

**Comment by aloysius-pgast** [comment]
Each event emitted by Bittrex contrains a sequence number which is incremented by 1 on each event. If library detects that an event has been missed ({last seq number} - {previous seq number} > 1), it will resync (retrieve full orderbook) and emit an `orderBook` event. If you call `client.resyncOrderBooks`, it is the same : full order book will be retrieved and `orderBook` event will be emitted

**Comment by artbred** [comment]
Great! Thank you very much

**Comment by artbred** [comment]
By the way maybe you can help me. When i use infinite loop to count some opportunities inside stock event emiters like orderbook or  orderbookupdate stops working, same with recursion. How its possible for them to work all the time besides infite loops or recursion?

**Comment by artbred** [comment]
The problem is that I have a class Bot that controls everything. When i start all websockets on pairs that i need i wait for 30 seconds to fetch for all order books, then i call other method of this class and listeners stops their work (i just write to the console event and pair). So when this method is done it starts its work one more time and i have no idea how to make it work all the time

**Comment by aloysius-pgast** [comment]
Without posting sample code, there is not much I can do
