### ISSUE TITLE
Difference between "trade" and "orderBookUpdate"

### ISSUE THREAD

**Issue by Henriii** [aloysius-pgast/bittrex-signalr-client#21]
Hi, 

First I want to thank you for creating this project, so far it works really good for me!

Now to my question:
Could you explain the difference between "trade" and "orderBookUpdates" events? From my understanding a trade would also trigger an orderBookUpdate, since it changes the orderbook on the exchange?!

Do I need to handle "trade" events when I want to keep a sync of an orderbook?

**Comment by aloysius-pgast** [comment]
Hi. Thanks for your feedback. Regarding the events :
* *trades* event will be emitted whenever some orders are fulfilled on exchange (ie: when orders are matched).
* *orderBook* & *orderBookUpdate* events are only related to new orders being submitted to the order book or removed from the order book

If you're interested in keeping your order book in sync, handling *orderBook* & *orderBookUpdate* is enough, you don't need to handle *trades* event (unless you also want to keep track of the orders which have been matched). 

When an order is matched, any exchange will emit both events :
* *trades* : since an order was fulfilled
* *orderBookUpdate* : since at least two entries in the order book have changed (because a *buy* order matched a *sell* order)

**Comment by Henriii** [comment]
Thank you! Much appreciated.
